env:
  commonjs: true
  es6: true
  node: true
extends: eslint:recommended
global:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2021
rules:
  no-unused-vars: [warn]
  semi: [warn, never]
  quotes: [warn, single]
  indent: [warn, 2, { SwitchCase: 1 }]
